### ISSUE TITLE
acceleration / deceleration

### ISSUE THREAD

**Issue by laurb9** [laurb9/StepperDriver#1]
The stepper motor can skip steps at high load if we apply constant step frequency, but is able to go faster more reliably if gradually accelerated to target rpm. Similarly, slowly braking can help the motor stop on the target instead of missing it due to load inertia.

**Comment by ben-hewitt** [comment]
Did you ever make any progress on sorting acceleration / deceleration? be suuuper useful!

**Comment by Heckthor** [comment]
Any update on this?

**Comment by laurb9** [comment]
I've been working on other things, but I might take a stab at it eventually. In the meantime, there is an AccelStepper library bundled with Arduino which can do this (it only needs the STEP pin).

The reference documentation for this feature would be the links below. I believe with the recent more powerful MCUs, there may be no need for formula approximations, however.
- http://www.embedded.com/design/mcus-processors-and-socs/4006438/Generate-stepper-motor-speed-profiles-in-real-time
- http://www.ti.com/lit/an/slyt482/slyt482.pdf
