### ISSUE TITLE
Please advice on constant rotation

### ISSUE THREAD

**Issue by vadimkim** [laurb9/StepperDriver#111]
Hi,
Is it possible to "turn motor ON/OFF" unless some external event happens?
I need to change rotation direction each time button is pushed. Right now I execute move(360) and check button state unless button is pressed in the loop. Movement is not smooth.

**Comment by laurb9** [comment]
You can try the NonBlocking example for more fine grained access between steps.

**Comment by vadimkim** [comment]
Thank you, @laurb9! It works!
