### ISSUE TITLE
StepperDriver with limit switch

### ISSUE THREAD

**Issue by brunnwart** [laurb9/StepperDriver#16]
Hi,

I'd like to start with the StepperDriver lib for the Pololu DRV8834 Driver Carrier.
Can anyone give me a hint how to 
1) setup()
- go backward as long as the limit switch is reached

2) loop()
- go xy steps forward or backward but never further than touching one of the 2 limit switches.

Thanks a lot in advance and many regards,
Brunnwart

**Comment by laurb9** [comment]
Sorry, that functionality is out of scope for this library.
