### ISSUE TITLE
dual-motor driver

### ISSUE THREAD

**Issue by laurb9** [laurb9/StepperDriver#2]
(investigate)

See if two motors can be moved to their respective targets at the same time, for a smooth two-axis rotation. Since motors have to draw current anyway even when not moving, power-wise this would not be a problem, but different rpms can make the timing interlacing difficult to implement.

**Comment by gohilurvish** [comment]
If implemented, it would be great for CNC users.

**Comment by laurb9** [comment]
I think this is relatively simple to do, although there will need to be a container class to do the management of multiple motors.
Need to see how to integrate accel/decel (#1) into this though, which might be trickier.

**Comment by laurb9** [comment]
Added two new classes for multi-motor drivers:
- MultiDriver drives each motor at its standard speed, so the motors finish at different times.
- SyncDriver where all motors are synced to reach their target at the same time.

I've not yet frozen the semantics of the calls, because #19 might result in some changes there.

**Comment by laurb9** [comment]
Note that multi-motor control only works well with CONSTANT_SPEED mode (#1)
MultiDriver *should* work with LINEAR_SPEED, but SyncDriver does not until I figure out the formulas to use for stretching the time.
