### ISSUE TITLE
Non blocking?

### ISSUE THREAD

**Issue by R5fan** [laurb9/StepperDriver#26]
The readme mentions nonblocking mode. Can you explain how this works, perhaps provide an example?

**Comment by laurb9** [comment]
This is an example of how it works. I plan to move the timing back into the polling function though, it doesn't seem right to rely on external timing. But it should work the same way.

https://github.com/laurb9/StepperDriver/blob/master/examples/AccelTest/AccelTest.ino

**Comment by laurb9** [comment]
Added NonBlocking example for 1.1.2
