### ISSUE TITLE
Nema 17 doesnt stay tough when it is idle

### ISSUE THREAD

**Issue by tominoll** [laurb9/StepperDriver#31]
hi,
i want to control a nema 17 with an a4988 and i need that when the motor doesnt recieve any step, it has to stay tough/hard.
When i tried it, the motor turns off when it doesnt recieves any step from the driver. 
This is a hardware or a software problem?? how can i solve it??

**Comment by laurb9** [comment]
Don't call stepper.disable()

**Comment by tominoll** [comment]
thanks, i forgot to put the "stepper.enable();"
