### ISSUE TITLE
DRV8825 Micro-Stepping

### ISSUE THREAD

**Issue by nadavmatalon** [laurb9/StepperDriver#34]
Hi laurb9,

First, great job on making this library! 

I may have spotted a tiny error I thought I'd bring to your attention regarding the DRV8825.

In the 'Microstepping' example code you comment that:

     * Microstepping mode: 1,2,4,8,16 or 32(DRV8834 only)

However, the DRV8825 also has the option for 32 micro-steps mode as the datasheet makes clear in the very first feature it lists on the front page (http://www.ti.com/lit/ds/symlink/drv8825.pdf).

All the best,
Nadav

**Comment by laurb9** [comment]
Thanks. That comment must have been left from before DRV8825 was added.
