### ISSUE TITLE
Fix Magic Numbers

### ISSUE THREAD

**Issue by nadavmatalon** [laurb9/StepperDriver#35]
Hi again,

I'm working with a 0.9 deg (400 steps) stepper motor and I've noticed your code contains a fair amount of 'magic' numbers in this context. That is, you have the number 200 in various places (see, e.g. the Microstepping example), or sometimes 100 when looking to rotate half a revolution (180 deg). 

Would be much cleaner and useful to employ the constant - which you've already defined at the beginning of the code (i.e. MOTOR_STEPS) - instead of those numbers. That way, users with 0.9 motors (or whatever) would only need to change a single value rather than going over the whole code and needing to calculate which value to enter at each point.

All the best,
Nadav

**Comment by laurb9** [comment]
Thanks, you are of course correct. Will replace 100 in Microstepping example with MOTOR_STEPS/2, and will fix the lone 200 in the BasicStepperDriver example.
