### ISSUE TITLE
Multiple stepper motors.

### ISSUE THREAD

**Issue by reycreator17** [laurb9/StepperDriver#38]
Hi. Thank you for your great work! I just want to ask how to set multiple stepper motors.

**Comment by carlosen14** [comment]
I am using SyncDriver from this library. You control up to 3 motors and the move at the same time.

**Comment by laurb9** [comment]
That's correct. You can use either MultiDriver or SyncDriver. MultiDriver works better if you don't need to follow a single line trajectory and works with both constant speed or acceleration. SyncDriver does not work well with acceleration.

Try the MultiAxis example.
