### ISSUE TITLE
Get Time For Move ?

### ISSUE THREAD

**Issue by carlosen14** [laurb9/StepperDriver#39]
Using the function `stepper.getTimeForMove(steps)` always gives 75 .. Doesn't matter if it is going to move 500 or 20,000 steps. 

Also, based on your example NonBlocking.ino you use 
```
    // motor control loop - send pulse and return how long to wait until next pulse
    unsigned wait_time_micros = stepper.nextAction();
```
but doing it this way it gives zero for both motors. I am thinking this could be because i am moving them using SyncDriver controller object.

I am using SyncDriver.h to control two motors at the same time and both moves to their destination without problem.

**Comment by laurb9** [comment]
You are correct, the getTimeForMove() was broken in commit db1c1f4, forgot to multiply by steps. Which probably means that SyncDriver is probably not working well either.

When you are using SyncDriver or MultiDriver, you use their nextAction() and no longer calling directly on the motors. So something like this:

```
SyncDriver controller(stepperX, stepperY);
controller.startRotate(360)
while (wait_time_micros = controller.nextAction()){
  // optional other code
}
```
