### ISSUE TITLE
Return steps left

### ISSUE THREAD

**Issue by Newjorciks** [laurb9/StepperDriver#45]
It would be useful to return the steps_remaining value in the stop() and startBrake() functions.
It will not affect current usages because they simply won't be capturing the returned value, and it can be useful for detecting position of where the stepper was.
One of use cases:
- I don't know the absolute position of the stepper.
- So I call a move with 1000 steps knowing that is enough to hit an end-stop.
- The motor hits an end-stop.
- I call stop() and receive back that there were still 400 steps left.
- Now I know that when I started moving it, it was 600 steps away.
- I can move it back to that position and now I know it's absolute position(600 steps).

**Comment by laurb9** [comment]
1.1.4 will have getStepsRemaining() and stop() returns the remaining steps as well.
Thank you for your suggestion and reasoning.
