### ISSUE TITLE
Use end-stop to set home(X+ & X-)

### ISSUE THREAD

**Issue by acmilan567** [laurb9/StepperDriver#54]
I'm looking for a way to get all the axes to the starting position, but I do not think it's possible using this library. is that it?

**Comment by laurb9** [comment]
Take a look at the NonBlocking.ino example. You have to use "non-blocking" mode and inside the loop check for the end condition. It's easy if you do each motor separately.

To use multiple motors at the same time, it doesn't have good support but it's possible - you would have to use MultiDriver combined with non-blocking mode and once triggered and stopped for each motor, repeat the startMove() with the remaining motors until all are clear.

**Comment by laurb9** [comment]
Closing, presumed resolved.
