### ISSUE TITLE
i need to use 8 motor 

### ISSUE THREAD

**Issue by nuedjidee** [laurb9/StepperDriver#56]
i need to use 8 step motor can use this library

**Comment by laurb9** [comment]
Do you have an 8-step or 8-wire motor ?

If you really have an 8 step motor, then you can set MOTOR_STEPS to 8 and it should work.

If you have an 8-wire stepper, take a look at [Adafruit's All About Stepper Motors](https://learn.adafruit.com/all-about-stepper-motors/types-of-steppers) page to learn how to wire it as a bipolar motor that the drivers can work with.

**Comment by nuedjidee** [comment]
I have 8 step motor not 8 wire motor

I want to control 8 motor

How I can set this library. Please tell me

Thank you sir

**Comment by nuedjidee** [comment]
this library can use 8 motor ?sir

**Comment by laurb9** [comment]
8 motors ? If you want to drive them sequentially, you can have as many as you want. But in parallel, the max the library does as implemented is 3. With some code changes it can do more but I do not support that use because you can run into timing issues.

**Comment by nuedjidee** [comment]
thank sir
