### ISSUE TITLE
count the number of steps

### ISSUE THREAD

**Issue by tharunjoy** [laurb9/StepperDriver#57]
Is there any way to count the number of step's a stepper motor using the library.

**Comment by laurb9** [comment]
do you mean the number of steps since initialization, since last move, or predicted steps for a move ?

**Comment by tharunjoy** [comment]
steps the motor has moved or the completed steps of the motor

**Comment by LewisMojica** [comment]
This would be a very useful feature.

**Comment by tognotommy** [comment]
I would also be interested in this feature, was thinking of implementing it myself. It would be for me however tracking the performed steps since last command issued probably, since I need to compare that value with encoder readings. If i do implement it i'll let you guys know :)

**Comment by laurb9** [comment]
Thank you everyone for your feedback. This method will be available in 1.1.4
