### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by laurb9** [laurb9/StepperDriver#80]
Set up for CI/CD

- Makefile
- arduino-builder (https://github.com/arduino/arduino-builder)
- jenkins, travis ci, ?? 
- no way to run automation in an arduino env ?

**Comment by gilmaimon** [comment]
Are you still looking for a way to Integrate Travis to your repo? I recently did it with 2 of my libraries. For my projects, the ci instructions run all the examples for each push and makes sure there are no compilation errors

**Comment by laurb9** [comment]
Thanks, I will check out your repos. 

I did take a look at travis-ci.com and it looks like they do have free open source option, but they request access into my orgs and private repos so I cannot allow it.

**Comment by gilmaimon** [comment]
I see. I didn't try other services, but I assume the use of arduino-cli will be similar.

**Comment by laurb9** [comment]
travis-ci responded and said they are in the process of fixing that, I am going to try it later this weekend.

> you can sign up and then immediately switch all your repositories over to the new Github Apps integration, which does not require write permissions to your private repos, and deauthorize the older integration which will revoke our write access entirely and allow you to use Travis.

**Comment by gilmaimon** [comment]
Cool! Well if you'll need any help with that I would love to assist.

**Comment by laurb9** [comment]
Thanks. I enabled the git apps for the repo and disabled the oauth token, looks like it should be ready to go. All I need is a `.travis.yaml` like this one right ? https://github.com/gilmaimon/ArduinoComponents/blob/master/.travis.yml

I'm going to start looking at this soon

**Comment by gilmaimon** [comment]
Yes that's right. Now, there are many improvements that could be made to my Travis file. For example a bash script that scans the examples folder so there will be no need to specify each test in the Travis file. And some other advanced Travis features I saw here and there, but the basics are as I did in the file you linked.

**Comment by laurb9** [comment]
Looks like it's working! thanks for the pointers, I ended up moving most of the tasks in a Makefile so it can be executed manually or in a docker container if need be.
