### ISSUE TITLE
Consider adding a badge from ArduBadge

### ISSUE THREAD

**Issue by gilmaimon** [laurb9/StepperDriver#81]
Hi, 
Consider adding this badge from [ArduBadge](https://www.ardu-badge.com):
[![arduino-library-badge](https://www.ardu-badge.com/badge/StepperDriver.svg?)](https://www.ardu-badge.com/StepperDriver)
Markdown:
`[![arduino-library-badge](https://www.ardu-badge.com/badge/StepperDriver.svg?)](https://www.ardu-badge.com/StepperDriver)`

It shows the latest version that is available on the Arduino IDE (and that the library is indeed in the IDE's Library Manager). Also, clicking on the badge redirects to a custom page with instructions for installing StepperDriver from the IDE and from a ZIP file.
Hope you liked it :)

**Comment by laurb9** [comment]
Thanks, I'll try it
