### ISSUE TITLE
Feature on a couple of function

### ISSUE THREAD

**Issue by GiuseppePorcheddu** [laurb9/StepperDriver#83]
**Is your feature request related to a problem? Please describe.**
No problem, only a suggestion

**Describe the solution you'd like**
Returns values on a couple of functions. I added return values on :
setRPM()
setSpeedProfile()
to get back directly the current value... e.g.

MyFunction() 
{
float oldRmp = setRPM(newRpm)
.... code
.... code
serRPM(oldRpm)
}

Attached the modified two files.

[ToImprove.zip](https://github.com/laurb9/StepperDriver/files/3089768/ToImprove.zip)

**Describe alternatives you've considered**
No one

**Additional context**

**Comment by laurb9** [comment]
Closing this ticket because now there are `getRPM()`, `getSpeedProfile()` etc so this functionality is available in a more explicit way.
