### ISSUE TITLE
Limit switches

### ISSUE THREAD

**Issue by trlafleur** [laurb9/StepperDriver#85]
Adding optional basic limit switch support to this library would be a big help....

If moving CW and CW limit is active, stop..... Etc..

Stop could be a hard or soft stop....

Thanks

**Comment by laurb9** [comment]
I'm concerned with adding specialized functionality to a library intended to be simple and generic. The [NonBlocking example](https://github.com/laurb9/StepperDriver/blob/master/examples/NonBlocking/NonBlocking.ino) shows one way to implement this.
